#A list of messages that if contained in a message will be stopped.
messages = ["You are using a beta version of Railcraft Reborn", "This game is using an alpha build of Ender IO", "This pack contains Observable", "Ars Nouveau adds bulit in", "Hello, and thank you for downloading Terralith!"]

