
[general]
	"Enable 'q' Button" = false
	#Set to false to disable the popup message telling you that you can config quark in the q menu
	"Enable Onboarding" = false

[automation]
	"Feeding Trough" = false
	"Pistons Move Tile Entities" = false

[management]
	"Inventory Sorting" = false

[tweaks]
	"Automatic Recipe Unlock" = false
	"Simple Harvest" = false

[world]
	"Big Stone Clusters" = false

[client]
	"Back Button Keybind" = false
